### ISSUE TITLE
refactor the google geocode function 

### ISSUE THREAD

**Issue by panzerama** [panzerama/Dispatch#35]
it takes in an address, it returns a LatLng, and that we know that the LatLng is absolutely populated with a value at the end. If it can’t be retrieved, or if there’s another issue, it should throw an error

**Comment by ljs4x** [comment]
Crisis object now has state for latitude and longitude. 
Usable LatLng can be created. 
Setting lat and long state can be done by following the framework set up by Panzerama in MainActivity
